services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MY_UID: ${MY_UID:-1001}
        MY_GID: ${MY_GID:-1001}
    ports:
      - "0.0.0.0:3103:3103" # Assuming the app runs on port 3103
    user: root
    env_file:
      - .env.production
    ports:
      - "3103:3103"
    env_file: .env
    environment:
      TZ: America/Sao_Paulo
      MYSQL_HOST: mysql
      MYSQL_USER: auth_api
      MYSQL_PASSWORD: senha123
      MYSQL_DATABASE: gigantao_auth_notify_prod
    depends_on:
      - mysql
    networks:
      - default
      - coolify # Connects to the external Coolify network for Redis and MySQL

networks:
  default:
    driver: bridge
  coolify:
    external: true # Indicates that the 'coolify' network already exists (created by Coolify)
